version: "2"

services:
    web:
        container_name: blogmvc_web
        image: nginx:latest
        env_file: ./docker/nginx/.env
        volumes:
            - ".:/home/docker"
            - "./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
        links:
            - fpm
        depends_on:
            - fpm

    database:
        container_name: blogmvc_database
        image: mysql:5.7
        env_file: ./docker/mysql/.env
        volumes:
            - blogmvc-data-mysql:/var/lib/mysql

    redis:
        container_name: blogmvc_redis
        image: redis:4.0
#        volumes:
#            - data-blogmvc-redis:/data

    redis-browser:
        container_name: blogmvc_redis_browser
        image: birkof/redis-browser
        links:
            - redis
        depends_on:
            - redis
        ports:
            - "4567:4567"
        command: --url redis://redis:6379 --bind 0.0.0.0

    fpm:
        container_name: blogmvc_fpm
        image: ismaail/php:7.2-alpine-fpm-dev
        volumes:
            - ".:/home/docker:rw"
        working_dir: "/home/docker"
        links:
            - database
            - redis
        depends_on:
            - database
            - redis

#
# Volumes definition
#
volumes:
    blogmvc-data-mysql:
        driver: local
#    data-blogmvc-redis:
#        driver: local

networks:
    default:
        external:
            name: nginx_reverse_proxy_network
