home:
    path: /
    controller: App\Controller\DefaultController::index
    methods: [GET]

post_show:
    path: /post/{slug}
    controller: App\Controller\DefaultController::show
    requirements:
        slug: "[a-zA-Z0-9-]+"
    methods: [GET]

post_comment_store:
    path: /post/{slug}/comment
    controller: App\Controller\CommentController::store
    requirements:
        slug: "[a-zA-Z0-9-]+"
    methods: [POST]

category_posts:
    path: /category/{slug}
    controller: App\Controller\DefaultController::byCategory
    requirements:
        slug: "[a-zA-Z0-9-]+"
    methods: [GET]

author_posts:
    path: /author/{username}
    controller: App\Controller\DefaultController::byAuthor
    requirements:
        username: "[a-zA-Z0-9-_]+"
    methods: [GET]

# Auth routes
login:
    path: /login
    controller: App\Controller\Auth\AuthController::login
    methods: [GET, POST]
