services:
    app.repository.post_repository:
        alias: App\Repository\PostRepository
        public: true
    app.repository.category_repository:
        alias: App\Repository\CategoryRepository
        public: true

framework:
    cache:
        pools:
            app_cache:
                adapter: cache.adapter.array
                provider: ~
